dockerApp/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|

// Route::get( '/{category}/{content}', function () {
//     return 'Hello World';
// });
*/

// ##################################### related to elasticsearch #####################################
Route::prefix('elasticsearch')->group(function(){
	Route::get('test', ['uses' => 'ClientController@elasticsearchTest']);
});


Route::get('/phpinfo', function() {
    exit(phpinfo());
});


// ##################################### Gray Wolf #####################################


// ##################################### Dashboard #####################################

Route::get('graywolf/dashboard', 'DashboardController@show')->name('dashboard.show')->middleware('auth');


// #####################################   Blogs   #####################################

Route::get('graywolf/blog/save', 'BlogController@showForm')->name('blog.showForm')->middleware('auth');

Route::post('graywolf/blog/save', 'BlogController@save')->middleware('auth');

Route::get('graywolf/blog/view', 'BlogController@view')->name('blog.view')->middleware('auth');

Route::post('graywolf/blog/remove', 'BlogController@remove')->middleware('auth');

Route::get('graywolf/blog/edit/{id}', 'BlogController@showEditForm')->name('blog.showEditForm')->middleware('auth');

Route::post('graywolf/blog/edit/{id}', 'BlogController@editBlog')->middleware('auth');

Route::get('graywolf/blog/kategoriler', 'BlogCategoryController@index')->name('blog.categoryIndex')->middleware('auth');

Route::post('graywolf/blog/kategoriler', 'BlogCategoryController@store')->middleware('auth');

Route::post('graywolf/blog/kategoriler/remove', 'BlogCategoryController@destroy')->middleware('auth');

Route::get('graywolf/blog/kategoriler/edit/{id}', 'BlogCategoryController@edit')->name('blog.editCategoryIndex')->middleware('auth');

Route::post('graywolf/blog/kategoriler/edit/{id}', 'BlogCategoryController@update')->middleware('auth');

// ##################################### Menus #####################################

Route::get('graywolf/menu/view', 'MenuController@index')->name('menu.index')->middleware('auth');

Route::post('graywolf/menu/view', 'MenuController@store')->middleware('auth');

Route::post('graywolf/menu/remove', 'MenuController@destroy')->middleware('auth');

Route::get('graywolf/menu/edit/{id}', 'MenuController@showEditForm')->name('menu.showEditForm')->middleware('auth');

Route::post('graywolf/menu/edit/{id}', 'MenuController@editMenu')->middleware('auth');

Route::post('graywolf/menu/sorting', 'MenuController@sorting')->middleware('auth');


// ##################################### Pages #####################################

Route::resource('graywolf/page','PageController')->except( ['store'] )->middleware('auth');

Route::post('graywolf/page/create', 'PageController@store')->middleware('auth');


// ##################################### Image Gallery #####################################


Route::resource('graywolf/imagegallery/images','ImageController')->except( ['destroy'] )->middleware('auth');

Route::post('graywolf/imagegallery/images/destroy', 'ImageController@destroy')->middleware('auth');

Route::resource('graywolf/imagegallery','ImageGalleryController')->middleware('auth');


// ##################################### User Logs #####################################

Route::resource('graywolf/userslogs','UsersLogsController')->middleware('auth');



// ##################################### Visitors Contact #####################################

Route::resource('contact','ContactController');


// ##################################### Products #####################################


Route::resource('graywolf/products','ProductController')->middleware('auth');







// ##################################### Authentication #####################################

// Authentication Routes...
Route::get('graywolf/login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('graywolf/login', 'Auth\LoginController@login');

Route::post('graywolf/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('graywolf/register', 'Auth\RegisterController@showRegistrationForm')->name('register');

Route::post('graywolf/register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('graywolf/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');

Route::post('graywolf/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

Route::get('graywolf/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::post('graywolf/password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('graywolf/users','UserController')->middleware('auth');






// ##################################### WebSite #####################################

//redis ile alakalı //
Route::get('/', 'WebsiteController@index' )->name('website.index');



Route::get('menu/{id}', 'MenuController@showArticle')->where('id', '[0-9]+');
Route::get('showblog', 'MenuController@showBlog');

// Route::get('/', function(){
// 	$redis = app()->make('redis');
// 	// $redis->set("key1","asfas");
// 	return $redis->get('key1');
// });

//redis ile alakalı //






Route::get('/sayfa/{page}', 'WebsiteController@page' )->name('website.page');

Route::get('/{category}', 'WebsiteController@category' )->name('website.category');

Route::get('/{menu}/{blog}', 'WebsiteController@content' )->name('website.content');
















// php artisan make:model usersLogs -a

dockerApp/app/ImageGallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ImageGallery extends Model
{
    protected $fillable = [
        'title', 'url', 'description', 'images', 'tags','subtitle'
    ];

    public function images()
	{
		return $this->hasMany('App\Image');
	}

	public function blogs()
	{
		return $this->hasMany('App\Blog');
	}

	public function pages()
	{
		return $this->hasMany('App\Page');
	}

}

dockerApp/app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
	public function show()
	{
		return view('dashboard.blog.show');
	}
}

dockerApp/app/Http/Controllers/ImageGalleryController.php
<?php

namespace App\Http\Controllers;

use App\ImageGallery;
use Illuminate\Http\Request;
use Session;
use App\Image;
use App\Http\Controllers\UsersLogsController;

class ImageGalleryController extends Controller
{
    private $photos_path;
 
    public function __construct()
    {
        $this->photos_path = public_path('/resim_galerileri');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $imageGalleries = ImageGallery::all();

        return view('dashboard.imageGallery.index', compact( 'imageGalleries' ) );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.imageGallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, UsersLogsController $usersLogs)
    {
        
        $this->validation($request);

        $imageGallery = ImageGallery::create($request->all());

        $usersLogs->store($request, $request['title'].' başlıklı resim galerisi kayıt etti.');

        return redirect('graywolf/imagegallery/images/'.$imageGallery->id.'/edit');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ImageGallery  $imageGallery
     * @return \Illuminate\Http\Response
     */
    public function show(ImageGallery $imageGallery)
    {
        return '3123';
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ImageGallery  $imageGallery
     * @return \Illuminate\Http\Response
     */
    public function edit(ImageGallery $imageGallery)
    {
        return '31231341';
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ImageGallery  $imageGallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ImageGallery $imageGallery)
    {
        return '35345234';
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ImageGallery  $imageGallery
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ImageGallery $imagegallery, UsersLogsController $usersLogs)
    {

        $imagegalleryId = $imagegallery->id;

        $uploaded_images = Image::where('image_gallery_id', $imagegalleryId)->get();
 
        if (!empty($uploaded_images)) {

            $path = $this->photos_path . '/' . $imagegallery->url;

            if(is_dir($path)){
                
                array_map( 'unlink', glob($path."/*") );
                
                rmdir($path);

            }

        }

        Image::where('image_gallery_id', $imagegalleryId)->delete();

        $title = $imagegallery->title;

        if ($imagegallery->delete()) {
            $usersLogs->store($request, $title.' başlıklı resim galerisini sildi.');
        }

        return back()->with('message','Resim Galerisi silindi!');

    }

    public function validation($request)
    {
        return $this->validate( $request, 
            [
                'title' => 'required|max:200',
                'url' => 'required|unique:image_galleries|max:150',
                'tags' => 'max:200',
                'description' => 'max:1000',
                'subtitle' => 'max:1000'
            ]
            ,[
                'title.required' => 'Başlığı boş bırakmayınız.',
                'title.max' => 'Başlık 200 karakterden uzun yazmayınız.', 
                'url.unique' => 'Uzantı zaten kayıtlı.', 
                'url.max' => 'Uzantı 150 karakterden uzun yazmayınız.', 
                'url.required' => 'Uzantıyı boş bırakmayınız.',
                'tags.max' => 'Etiketler 200 karakterden fazla olamaz.',
                'description.max' => 'Açıklama 1000 karakterden fazla olamaz.',
                'subtitle.max' => 'Alt Başlık 1000 karakterden fazla olamaz.'
            ]
        );
    }
}

dockerApp/resources/views/dashboard/imageGallery/create.blade.php
@extends('dashboard.app')



@section('addcss')
    <link rel="stylesheet" href="/css/dropzone.css">
    <link rel="stylesheet" href="/css/tagsinput.css">
@endsection



@section('addjs')
	<script type="text/javascript" src="/js/tagsinput.js"></script>
	<script src="/js/dropzone.js"></script>
  	<script src="/js/forms_file-upload.js"></script>
  	<script type="text/javascript">
  		function slug(str) {
		  str = str.replace(/^\s+|\s+$/g, ''); // trim
		  str = str.toLowerCase();

		  // remove accents, swap ñ for n, etc
		  var from = "ãàáäâẽèéëêìíïîõòóöôùúüûñçşIĞğı·/_,:;";
		  var to   = "aaaaaeeeeeiiiiooooouuuuncsiggi------";
		  for (var i=0, l=from.length ; i<l ; i++) {
		    str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
		  }

		  str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
		    .replace(/\s+/g, '-') // collapse whitespace and replace by -
		    .replace(/-+/g, '-'); // collapse dashes

		  return str;
		};
		$("#title").keyup(function(){
	        $("#url").val( slug( $(this).val() ) );
	    });
	    (function() {
			'use strict';
			window.addEventListener('load', function() {
			  var form = document.getElementById('needs-validation');
			  form.addEventListener('submit', function(event) {
			    if (form.checkValidity() === false) {
			      event.preventDefault();
			      event.stopPropagation();
			    }
			    form.classList.add('was-validated');
			  }, false);
			}, false);
		})();
    	// You'd better put the code inside ready() function
  	</script>
@endsection




@section('content')
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
		<h1 class="h2">Resim Galerisi</h1>
		<p>
		  <a class="btn btn-secondary"  href="{{ route('imagegallery.index') }}">
		    Resim Galerilerini Görüntüle
		  </a>
		  <a class="btn btn-secondary disabled"  href="{{ route('imagegallery.create') }}">
		    Resim Galerisi Kayıt Et
		  </a>
		</p>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{{ route('imagegallery.index') }}">Resim Galerileri</a></li>
		    	<li class="breadcrumb-item active" aria-current="page">Resim Galerileri Formu</li>
			</ol>
		</nav>
	</div>
	@if ($errors->any())
	    <div class="alert alert-danger">
	        <ul>
	            @foreach ($errors->all() as $error)
	                <li>{{ $error }}</li>
	            @endforeach
	        </ul>
	    </div>
	@endif
	@if(Session::has('message'))
		<div class="alert alert-success fade in alert-dismissible show" style="margin-top:18px;">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    	<span aria-hidden="true" style="font-size:20px">×</span>
		  	</button>
		  	{{ Session::get('message') }}
		</div>
	@endif

	<div class="row">
		<div class="col-lg-12">
			{!! Form::open(['method' => 'POST', 'novalidate', 'id' => 'needs-validation', 'action' => 'ImageGalleryController@store']) !!}
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							{{ Form::label( 'title', 'Başlık', [] ) }}
							{{ Form::text('title', old('title'), ['placeholder' => 'Galeri adını giriniz.', 'maxlength' => '200', 'class' => 'form-control', 'id' => 'title', 'required'] ) }}
							<div class="invalid-feedback">
			                	Başlığı boş bırakmayınız.
			                </div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="form-group">
							{{ Form::label( 'url', 'Uzantı', [] ) }}
							{{ Form::text('url', old('url'), ['placeholder' => 'Uzantı kendiliğinden oluşacaktır.', 'maxlength' => '150', 'class' => 'form-control', 'id' => 'url', 'readonly', 'required'] ) }}
							<div class="invalid-feedback">
			                	Uzantıyı boş bırakmayınız.
			                </div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							{{ Form::label( 'subtitle', 'Alt Başlık', [] ) }}
							{{ Form::text('subtitle', old('subtitle'), ['placeholder' => 'Galeri alt başlığını giriniz.', 'maxlength' => '200', 'class' => 'form-control', 'id' => 'subtitle'] ) }}
						</div>
					</div>
					<div class="col-lg-6">
						<div class="form-group">
							{{ Form::label( 'description', 'Google için Açıklama', [] ) }}
							{{ Form::text('description', old('description'), ['placeholder' => 'Açıklama giriniz.', 'class' => 'form-control', 'id' => 'description'] ) }}
							<div class="invalid-feedback">
			                	Açıklamayı boş bırakmayınız.
			                </div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							{{ Form::label( 'tags', 'Etiketler' ) }}
							{{ Form::text('tags', old('tags'), ['placeholder' => 'Etiket giriniz.', 'class' => 'form-control', 'maxlength' => '200', 'id' => 'tags', 'data-role' => 'tagsinput'] ) }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						{{ Form::submit('Kayıt Et', ['class' => 'btn btn-info col-lg-12', 'id' => 'buttonSaveForm']) }}
					</div>
				</div>
			{!! Form::close() !!}
			
		</div>
	</div>
	

	
@endsection

{{-- 

<!DOCTYPE html>

<html lang="en" class="default-style">

<head>
  <title>File upload - Forms - Appwork</title>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="/js/dropzone.js"></script>
  	<script src="/js/forms_file-upload.js"></script>

  <link rel="stylesheet" type="text/css" href="/css/dropzone.css">
</head>

<body>
  
<form action="/upload" class="dropzone needsclick" id="dropzone-demo">
  <div class="dz-message needsclick">
    Drop files here or click to upload
    <span class="note needsclick">(This is just a demo dropzone. Selected files are
      <strong>not</strong> actually uploaded.)</span>
  </div>
  <div class="fallback">
    <input name="file" type="file" multiple>
  </div>
</form>

</body>

</html> --}}

dockerApp/resources/views/dashboard/imageGallery/index.blade.php
@extends('dashboard.app')

@section('content')
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
		<h1 class="h2">Resim Galerisi</h1>
		<p>
		  <a class="btn btn-secondary disabled"  href="{{ route('imagegallery.index') }}">
		    Resim Galerilerini Görüntüle
		  </a>
		  <a class="btn btn-secondary"  href="{{ route('imagegallery.create') }}">
		    Resim Galerisi Kayıt Et
		  </a>
		</p>
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		    <li class="breadcrumb-item"><a href="{{ route('imagegallery.index') }}">Resim Galerileri</a></li>
		  </ol>
		</nav>
	</div>
	@if(Session::has('message'))
		<div class="alert alert-success fade in alert-dismissible show" style="margin-top:18px;">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    	<span aria-hidden="true" style="font-size:20px">×</span>
		  	</button>
		  	{{ Session::get('message') }}
		</div>
	@endif
	<table id="datatables" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Başlık</th>
                <th>Açıklama</th>
                <th>Oluşturulma Tarihi</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach ($imageGalleries as $imagegallery)

                <tr>
                    <td>{{ $imagegallery->id }}</td>
                    <td>{{ $imagegallery->title }}</td>
                    <td>{{ $imagegallery->description }}</td>
                    <td>{{ $imagegallery->created_at }}</td>
                    <td>
                    	<span class="badge badge-pill badge-danger col-md-3" onclick="removeButtonClicked({{ $imagegallery->id }})" data-toggle="modal" data-target="#removeBlogModal">Sil</span>
                    	<span class="badge badge-pill badge-warning col-md-3"><a href="{{ route('images.edit',$imagegallery->id) }}">Değiştir</a></span>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>Id</th>
                <th>Başlık</th>
                <th>Açıklama</th>
                <th>Oluşturulma Tarihi</th>
                <th>İşlemler</th>
            </tr>
        </tfoot>
    </table>
	<div class="modal fade" id="removeBlogModal" tabindex="-1" role="dialog" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLongTitle">Sayfa Silme İşlemi</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        Evete tıklarsanız, sayfayı silmiş olacaksınız. Emin misiniz?
	        <input type="hidden" id="imageGalleryId" >
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Hayır</button>
	        <button type="button" class="btn btn-primary" id="removeBlog" >Evet</button>
	      </div>
	    </div>
	  </div>
	</div>

@endsection

@section('addcss')
	<link rel="stylesheet" href="/css/dataTables.bootstrap4.min.css">
	<style type="text/css">
		.badge-danger{
			cursor: pointer;
		}
	</style>
@endsection

@section('addjs')
	<script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="/js/dataTables.bootstrap4.min.js"></script>
	<script type="text/javascript">
		function removeButtonClicked(imageGalleryId){
			$('#imageGalleryId').val(imageGalleryId);
		}
		function postAndRedirect(url, postData)
		{
		    var postFormStr = "<form method='POST' action='" + url + "'>\n";
		    for (var key in postData)
		    {
		        if (postData.hasOwnProperty(key))
		        {
		            postFormStr += '<input type="hidden" name="id" value="' + postData + '"></input>'+'@csrf'+'@method("DELETE")';
		        }
		    }
		    postFormStr += "</form>";

		    var formElement = $(postFormStr);

		    $('body').append(formElement);

		    $(formElement).submit();

		}
		$(document).ready(function() {
			$('#removeBlog').click(function(){
				$('#removeBlogModal').modal('hide');
				postAndRedirect( '/graywolf/imagegallery/'+$('#imageGalleryId').val(), $('#imageGalleryId').val() );
				// postAndRedirect( '/graywolf/imagegallery/6', '6' );
			});
		    $('#datatables').DataTable({
		    	"order": [[ 3, "desc" ]]
		    });
		});
	</script>
	
@endsection